# Generated by Django 3.2.3 on 2022-03-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='number_bank',
            field=models.CharField(default='', max_length=22),
        ),
    ]
