# Generated by Django 3.2.8 on 2022-03-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Privates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=2)),
                ('body', models.TextField()),
                ('time', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=1)),
                ('recvId', models.CharField(max_length=1)),
                ('recvIsGroup', models.BooleanField(default=True)),
                ('_id', models.CharField(max_length=100)),
                ('_from', models.IntegerField()),
                ('_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.IntegerField(default=1)),
                ('to', models.IntegerField(default=1)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('from_name', models.CharField(default='', max_length=30)),
                ('to_name', models.CharField(default='', max_length=30)),
                ('unread', models.BooleanField(default=False)),
                ('subject', models.CharField(default='Saludo', max_length=250)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Attachments')),
                ('message_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message_email')),
            ],
        ),
    ]
