# Generated by Django 3.2.8 on 2022-03-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('second_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('block', models.BooleanField(default=False)),
                ('img', models.ImageField(default='Photo_Profile_Student/photo.jpg', upload_to='Photo_Profile_Student')),
                ('type', models.CharField(default='Student', max_length=10)),
            ],
        ),
    ]
